name: Build OpenWrt Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { 
              tag: "22.03.5",
              target: "ramips",
              subtarget: "mt7621",
              pkgarch: "mipsel_24kc",
              vermagic: "218bf6e00a546ab5c6ea465b29f9c777",
              sdk_url: "https://downloads.openwrt.org/releases/22.03.5/targets/ramips/mt7621/openwrt-sdk-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
            }
          # Добавьте другие архитектуры по необходимости
          # - { 
          #     tag: "22.03.5",
          #     target: "x86",
          #     subtarget: "64",
          #     pkgarch: "x86_64",
          #     vermagic: "a9d0f1e3",
          #     sdk_url: "https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
          #   }

    steps:
      - uses: actions/checkout@v4

      - name: Download OpenWrt SDK
        run: |
          wget ${{ matrix.config.sdk_url }} -O sdk.tar.xz
          tar -xf sdk.tar.xz
          mv openwrt-sdk-* sdk

      - name: Setup build environment
        run: |
          echo "VERMAGIC=${{ matrix.config.vermagic }}" >> $GITHUB_ENV
          sed -i "s/VERMAGIC:=.*/VERMAGIC:=${{ matrix.config.vermagic }}/" sdk/include/kernel-version.mk

      - name: Build package
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp -r ../package ./feeds/packages/net/domain-routing
          make package/domain-routing/compile \
            V=sc \
            PKG_ARCH=${{ matrix.config.pkgarch }} \
            TARGET=${{ matrix.config.target }} \
            SUBTARGET=${{ matrix.config.subtarget }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.config.target }}-${{ matrix.config.subtarget }}
          path: sdk/bin/packages/*/base/*.ipk
